[package]
name = "rustm"
version = "0.1.0"
edition = "2024"


[dependencies]
cursive = "0.21"
dirs = "6"
serde = { version = "1.0", features = ["derive"] }
serde_norway = "0.9"
log = "0.4"
simplelog = "0.12"
git2 = "0"
