[package]
name = "rustm"
version = "0.1.0"
edition = "2024"

[dependencies]
inquire = "0"
anyhow = "1"
log = "0"
simplelog = "0"
joy-error = { git = "https://github.com/sub07/rust-utils", version = "0.5.0", features = ["log-crate"] }
itertools = "0"
dirs = "6"
serde = {version = "1", features = ["derive"] }
serde_norway = "0"
cargo_toml = "0"
reqwest = { version = "0", features = ["blocking", "json", "rustls-tls"], default-features = false }
easy-ext = "1"
toml = "0"
toml_edit = "0"
assert_matches = "1"
